# Generated by Django 4.0.3 on 2022-03-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FigureModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.CharField(max_length=250)),
                ('brand', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('SD', 'SD Gundam'), ('MG', 'Master Grade'), ('HG', 'High Grade'), ('NG', 'No Grade')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
