# Generated by Django 4.0.3 on 2022-03-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FigureModels',
            new_name='Figure',
        ),
    ]
